"""initial

Revision ID: 542dbe876048
Revises: d33ff1f134ec
Create Date: 2023-06-09 18:27:45.754627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '542dbe876048'
down_revision = 'd33ff1f134ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
